model: mlp
dataset_name: community
loss_type: thomas_lq
range_size: 50
batch_size: 32
devices: 1
lr: 1e-4
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: 1, 5
max_epochs: 3000
ablation_param: "lq_norm_val"
ablation_values: 0.01, .02, .03, .05, .1, .15, .2, .25, .3, .4, .5, .6, .7, .8, 1.0, 1.25, 1.5, 1.75, 2, 2.5, 3
ablation_name: ablation_community_q