model: mlp
model_path: bio_11
dataset_name: bio
loss_type: thomas_lq
range_size: 50
batch_size: 16
devices: 1
lr: 1e-5
ffn_activation: relu
ffn_hidden_dim: 2500
ffn_num_layers: 4
constraint_weights: 1, 5
max_epochs: 5000
lq_norm_val: .5
weight_decay: 1e-4
optimizer: adamw