model: mlp
model_path: bio_model_two_moments_1051_weights_2000d_smaller_range
dataset_name: bio
num_moments: 2
range_size: 30
batch_size: 64
max_epochs: 2000
constraint_weights: 1, 10, 5
lr_scheduler: cosine
ffn_activation: relu
ffn_hidden_dim: 2000
ffn_num_layers: 4
lr: 5e-6
dropout_prob: .25 
devices: 1