model: mlp
model_path: community_2
dataset_name: community
loss_type: thomas_lq
range_size: 100
batch_size: 1
devices: 1
lr: 1e-4
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: 1, 5
max_epochs: 5000
lq_norm_val: .5
optimizer: adamw
weight_decay: 1e-4