model: mlp
model_path: concrete_13
dataset_name: concrete
loss_type: thomas_lq
optimizer: adamw
range_size: 50
batch_size: 16
devices: 1
lr: 1e-7
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: .05, 1
max_epochs: 10000
lq_norm_val: .5
weight_decay: 1e-2
dropout_prob: .05