batch_size: 32
constraint_weights: 1, 1
annealing_epochs: 450
annealing: True
dataset_name: concrete
devices: 1
early_stopping: false
ffn_activation: relu
ffn_hidden_dim: 1024
ffn_num_layers: 4
loss_type: thomas_lq
lq_norm_val: 0.5
lr: 0.001
max_epochs: 500
model: mlp
model_path: concrete_annealing_1.yaml
range_size: 50
