batch_size: 32
constraint_weights: 1, 5
annealing_epochs: 2500
annealing: True
dataset_name: concrete
devices: 1
ffn_activation: relu
ffn_hidden_dim: 2048
ffn_num_layers: 4
loss_type: thomas_lq
lq_norm_val: 0.5
lr: 0.001
max_epochs: 3000
model: mlp
model_path: concrete_annealing_3
range_size: 150
