model: mlp
model_path: concrete_12_again4
dataset_name: concrete
loss_type: thomas_lq
optimizer: adamw
range_size: 50
batch_size: 16
devices: 1
lr: 1e-7
ffn_activation: relu
ffn_hidden_dim: 2000
ffn_num_layers: 4
constraint_weights: .1, 1
max_epochs: 5000
lq_norm_val: .5
weight_decay: 1e-2
dropout_prob: .05