model: mlp
model_path: concrete_19
dataset_name: concrete
loss_type: thomas_lq
range_size: 100
batch_size: 32
devices: 1
lr: 1e-6
ffn_activation: relu
ffn_hidden_dim: 2000
ffn_num_layers: 4
constraint_weights: .25, 5
max_epochs: 5000
lq_norm_val: .1
optimizer: adamw
weight_decay: 1e-4