model: mlp
model_path: parkinsons_ori_2
dataset_name: parkinsons
loss_type: special_lq
range_size: 50
batch_size: 32
devices: 1
lr: 1e-7
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: .5, 5
max_epochs: 3000
lq_norm_val: .5
weight_decay: 1
optimizer: adamw
