model: resnet
model_path: cv_1
dataset_name: cuteness
loss_type: special_lq
range_size: 50
batch_size: 256
devices: 1
lr: 1e-4
constraint_weights: 1, 5
max_epochs: 3000
lq_norm_val: .5
weight_decay: 1e-4
optimizer: adamw
