model: mlp
model_path: meps_19_ce
dataset_name: meps_19
loss_type: crossentropy
range_size: 50
batch_size: 32
devices: 0
lr: 1e-8
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: 0, 1
max_epochs: 3000
lq_norm_val: .5
weight_decay: 1e-3
optimizer: adamw
