model: mlp
model_path: meps_20_ce
dataset_name: meps_20
loss_type: cross_entropy
range_size: 50
batch_size: 256
devices: 0
lr: 1e-7
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: 0, 1
max_epochs: 3000
lq_norm_val: .5
