batch_size: 32
constraint_weights: 1, 5
dataset_name: log_normal
devices: 0
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
loss_type: reverse
lq_norm_val: 0.5
lr: 0.0001
max_epochs: 3000
model: mlp
model_path: log_normal_reverse
optimizer: adamw
range_size: 50
weight_decay: 0.0001
