batch_size: 32
constraint_weights: 1, 1
dataset_name: concrete
devices: 1
ffn_activation: relu
ffn_hidden_dim: 256
ffn_num_layers: 2
loss_type: thomas_lq
lq_norm_val: 1
lr: 0.001
max_epochs: 2000
model: mlp
model_path: search_concrete_33
range_size: 50
