batch_size: 32
constraint_weights: 1, 20
dataset_name: concrete
devices: 1
ffn_activation: relu
ffn_hidden_dim: 1024
ffn_num_layers: 5
loss_type: thomas_lq
lq_norm_val: 0.25
lr: 0.001
max_epochs: 5000
model: mlp
model_path: search_concrete_again_68
range_size: 50
