model: mlp
model_path: lei_5
dataset_name: lei
loss_type: thomas_lq
range_size: 100
batch_size: 16
devices: 1
lr: 1e-5
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: .25, 5
max_epochs: 3000
lq_norm_val: .1
plot_dcp: True
weight_decay: 1e-3
optimizer: adamw