model: mlp
model_path: parkinsons_mle_we
dataset_name: parkinsons
loss_type: simplest
range_size: 50
batch_size: 8
devices: 0
lr: 1e-4
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: 1, 5
max_epochs: 3000
weight_decay: 1e-4
optimizer: adamw
lq_norm_val: .5
