model: mlp
model_path: concrete_ori
dataset_name: concrete
loss_type: thomas_lq
range_size: 50
batch_size: 32
devices: 1
lr: 1e-4
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: 1, 5
max_epochs: 3000
lq_norm_val: .5