model: mlp
model_path: solar_ori_3
dataset_name: solar
loss_type: special_lq
batch_size: 32
constraint_weights: .25, 5
devices: 0
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
lq_norm_val: 0.5
lr: 0.00001
max_epochs: 1000
optimizer: adamw
range_size: 150
weight_decay: 0.001
