batch_size: 32
constraint_weights: 0, 1
dataset_name: concrete
devices: 1
early_stopping: false
ffn_activation: relu
ffn_hidden_dim: 2048
ffn_num_layers: 4
loss_type: thomas_lq
lq_norm_val: 0.25
lr: 0.001
max_epochs: 500
model: mlp
model_path: search_concrete_aga2_ne_39
range_size: 100
