model: mlp
model_path: breastcancer_ori_2
dataset_name: breastcancer
loss_type: thomas_lq
range_size: 50
batch_size: 8
devices: 1
lr: 1e-5
ffn_activation: relu
ffn_hidden_dim: 500
ffn_num_layers: 4
constraint_weights: .5, 5
max_epochs: 5000
weight_decay: 1e-2
optimizer: adamw
lq_norm_val: .5
