model: mlp
model_path: parkinsons_ori_2
dataset_name: parkinsons
loss_type: special_lq
range_size: 100
batch_size: 8
devices: 1
lr: 1e-4
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: .5, 5
max_epochs: 3000
weight_decay: 1e-4
optimizer: adamw
lq_norm_val: .5
