model: mlp
model_path: pendulum_ori
dataset_name: pendulum
loss_type: thomas_lq
range_size: 50
batch_size: 32
devices: 1
lr: 1e-4
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
constraint_weights: 1, 5
max_epochs: 3000
weight_decay: 1e-4
optimizer: adamw
lq_norm_val: .5
