batch_size: 32
constraint_weights: 0, 1
dataset_name: meps_21
devices: 1
ffn_activation: relu
ffn_hidden_dim: 1000
ffn_num_layers: 4
loss_type: cross_entropy
lq_norm_val: 0.5
lr: 0.0001
max_epochs: 2
model: mlp
model_path: meps_21_sm
optimizer: adamw
range_size: 50
weight_decay: 0.0001
